# enable the memory-related functions in the crate
# allows us to recompile 'core' and other standard library crates on demand
[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

# avoid passing --target on every invocation
[build]
target = "x86_64-rust_os.json"